# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 75f79104c9e2c03c51d3a91d13336b2a8bb203e4

{
  "title": "Стол IKEA",
  "description": "Дуб"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token 75f79104c9e2c03c51d3a91d13336b2a8bb203e4

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 31b1f98ddcfc36fc7c8d7b8d92aab098d5649170

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2023-11-22
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json
