name: Autodeploy

on:
  push:
    branches: [video]

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DEBUG: ${{ secrets.DEBUG }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    services:
      postgres_db:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверка изменений
        uses: actions/checkout@v3

      - name: Установка питона, окружения
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Установка пакетов пип
        run: pip install -r 3.2-crud/stocks_products/requirements.txt

      - name: Линтинг
        run: flake8 3.2-crud/stocks_products/logistic/ --exclude logistic/migrations/

      - name: Тестирование
        run: python 3.2-crud/stocks_products/manage.py test
        env:
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASS: ${{ env.DB_PASS }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}